### ISSUE TITLE
Unknown error on Polyjuice (not encountered in Rinkeby)

### ISSUE THREAD

**Issue by haxyz** [nervosnetwork/polyjuice-provider#34]
Hello Folks at Nervos,
some tests on a [solidity contract](https://github.com/haxyz/sisyphus-gamble-v1-core/blob/master/SisyphusGamble.sol#L57) run just fine on Rinkeby, but they time out on Polyjuice.

To reproduce the error feel free to use this repository: https://github.com/haxyz/sisyphus-gamble-v1-tests

### Full output on Polyjuice
```
haxyz@nervos-workstation:~/sisyphus-gamble-v1-tests$ node index.js Polyjuice
Using Polyjuice network
Checking Balance...
Checking WETH Balance...
Approving WETH usage...
Txn Hash: 0x3a231dc9c56b3035955361e937740eb41f1d83a6b7f5c4c5a95ba6a17a01dd3b
new Sisyphus Gamble...
Txn Hash: 0x6f1347259b24f932be7a0db8722f8a5d0f74ad16a2eb67d731395c1f424cfd4d
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (/home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at /home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-method/lib/index.js:416:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  receipt: undefined
}
```
### Full output on Rinkeby
```
haxyz@nervos-workstation:~/sisyphus-gamble-v1-tests$ node index.js Rinkeby
Using Rinkeby network
Checking Balance...
Checking WETH Balance...
Approving WETH usage...
Txn Hash: 0x1988cb483325f7bb02a799d0dcae8208cc81ec6bb1f167a285e2ec5c85cc2a60
new Sisyphus Gamble...
Txn Hash: 0x1397b58390992c4d7ac74ecee785c5492d21bf94e9d3464ff4bf82a2c987fa66
Getting Sisyphus Gamble Venues...
Approving WETH usage...
Txn Hash: 0x8a090b1aa792c5b65004fea2341f95eb701ab0937aa3a90be86b7b8805c1bece
Calling gamble...
Txn Hash: 0xf5e0bf3412f4e837ac04e985e5a1b802ff5ecd26a723023f0f612531f9e951c2
Claiming prize...
Txn Hash: 0x72c5f29a5e11d37539c9ac2eb41fb048ba37fb6f36dceb38bccc9cdcc2affd13
```

**Comment by RetricSu** [comment]
hi, we will take a look at this soon. thanks for reporting. btw, if you want to debug more, you can try with [godwoken-kicker](https://github.com/RetricSu/godwoken-kicker) first to see if it works on local devent.

**Comment by haxyz** [comment]
Nice package!! You read my mind, I was about to ask in discord if such package exist 💪

By the way, my guess is that this bug is more on the godwoken-polyjuice side than polyjuice-provider one. Let me know if I should close it here and opened it there.

**Comment by RetricSu** [comment]
I try on my local devnet with kicker, it seems the new Sisyphus Gamble tx is failed, that's the reason why fetching receipt get timeout. and this, like you said, is a polyjuice issue. 

polyjuice logs:

```sh
2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: BEGIN parse_message()
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: args_len => 216
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [call_kind] => 0
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [gas_limit] => 6000000
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [gas_price] => 1
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [input_size] => 164
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: END parse_message()
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: load_account_script, account_id: => 10
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: load_account_script, account_id: => 3
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: rollup_script_hash 0x2e326ab6d4c0f90b83aa5896fa6fd31ee26597f00f715876235106b68c07008d
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: sudt id => 1
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [handle_message] BEGIN handle_message
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: load_account_script, account_id: => 10
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [load_account_code] account_id: => 10
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: sender 0x24f1de0c7084a2fb17a205282a8cd046e9fff047
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: destination 0xd19344fdf09d72bb7c2a9a59908a0ca3e2a12d94
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: transfer value => 0
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [handle_message] msg.kind => 0
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [execute_in_evmone] code size => 5138
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [execute_in_evmone] input_size => 164
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [handle_message] output size => 0
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [handle_message] gas left => 5999763
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [handle_message] used_memory(Bytes) => 96
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [handle_message] status_code => 2
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: [handle_message] END handle_message
godwoken_1      | [2021-09-01T09:10:55Z DEBUG gw_generator::syscalls] [contract debug]: handle message failed
godwoken_1      | [2021-09-01T09:11:00Z INFO  gw_block_producer::runner] received new layer1 block 1067, afc7016e4252de52a0acf5fbcc7969ba4cddd6fefdbee3d2383b48225e04fba2
```

I am transfering this issue to polyjuice repo. 

at the same time, since it is hard to debug on testnet right now, I will have to ask you to try providing a re-produciable example aims for devnet environment(including deploy the smart-contract and fill right env for the scripts to run).
